export const experimentsPagesDetails = [
  {
    path: "container-queries",
    title: "Container Queries",
    bgColor: "--violet-1-oklch-25",
    textColor: "--violet-1-oklch-full",
    illustration: "Saly-20.png",
    tags: ["css", "experiment", "html"],
    deployed: false,
    coming: false,
  },
  {
    path: "css-layers",
    title: "CSS Layers",
    bgColor: "--pink-1-oklch-25",
    textColor: "--pink-1-oklch-full",
    illustration: "Saly-11.png",
    tags: ["css", "experiment"],
    deployed: false,
    coming: false,
  },
  {
    path: "has-selector",
    title: ".has() selector",
    bgColor: "--blue-1-darker-1-oklch-25",
    textColor: "--blue-1-darker-1-oklch-full",
    illustration: "Saly-8.png",
    tags: ["css", "experiment", "selector"],
    deployed: false,
    coming: false,
  },
  {
    path: "view-transitions",
    title: "View transitions",
    bgColor: "--purple-1-oklch-25",
    textColor: "--purple-1-oklch-full",
    illustration: "Saly-1.png",
    tags: ["css", "experiment", "html"],
    deployed: false,
    coming: true,
  },
  {
    path: "subgrid",
    title: "Subgrid",
    bgColor: "--blue-1-darker-1-oklch-25",
    textColor: "--blue-1-darker-1-oklch-full",
    illustration: "Block_Matrix_x3_0003.png",
    tags: ["css", "experiment", "grid"],
    deployed: false,
    coming: false,
  },
  {
    path: "web-components",
    title: "Web Components",
    bgColor: "--violet-1-oklch-25",
    textColor: "--violet-1-oklch-full",
    illustration: "rocket.png",
    tags: ["html", "experiment", "npm"],
    deployed: false,
    coming: false,
  },
  {
    path: "oklch",
    title: "oklch() color",
    bgColor: "--pink-1-oklch-25",
    textColor: "--pink-1-oklch-full",
    illustration: "3d-plastic-people-tv.png",
    tags: ["css", "experiment", "color"],
    deployed: false,
    coming: true,
  },
  {
    path: "color-mix",
    title: "color-mix() function",
    bgColor: "--purple-1-oklch-25",
    textColor: "--purple-1-oklch-full",
    illustration: "3d-plastic-people-tv.png",
    tags: ["css", "experiment", "color"],
    deployed: false,
    coming: true,
  },
];
