export const experimentsPagesDetails = [
  {
    path: "container-queries.astro",
    title: "Container Queries",
    bgColor: "--violet-1-oklch-25",
    textColor: "--violet-1-oklch-full",
    illustration: "Saly-20.png",
    tags: ["css", "experiment", "html"],
  },
  {
    path: "css-layers.astro",
    title: "CSS Layers",
    bgColor: "--red-1-oklch-25",
    textColor: "--red-1-oklch-full",
    illustration: "Saly-11.png",
    tags: ["css", "experiment"],
  },
  {
    path: "has-selector.astro",
    title: ".has() selector",
    bgColor: "--blue-1-oklch-25",
    textColor: "--blue-1-oklch-full",
    illustration: "Saly-8.png",
    tags: ["css", "experiment"],
  },
  {
    path: "subgrid.astro",
    title: "Subgrid",
    bgColor: "--pink-1-oklch-25",
    textColor: "--pink-1-oklch-full",
    illustration: "Saly-17.png",
    tags: ["css", "experiment", "grid"],
  },
  {
    path: "view-transitions.astro",
    title: "View transitions",
    bgColor: "--purple-1-oklch-25",
    textColor: "--purple-1-oklch-full",
    illustration: "Saly-1.png",
    tags: ["css", "experiment", "html"],
  },
  {
    path: "oklch.astro",
    title: "oklch() color",
    bgColor: "--violet-1-oklch-25",
    textColor: "--violet-1-oklch-full",
    illustration: "3d-plastic-people-tv.png",
    tags: ["css", "experiment", "color"],
  },
];
